# Site settings
title: Centrum Stomatologiczne Bema 4
email: stomatologia@bema4.pl
description: > # this means to ignore newlines until "baseurl:"
  Centrum zlokalizowane jest w sercu Gdyni. Starannie dobrany zespół
  lekarzy przy współpracy z dyplomowanymi higienistkami zapewni państwu
  opiekę stomatologiczną na najwyższym poziomie.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.bema4.pl" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

collections:
 - slides
 - team